Side menu
zenitheesc/Obsite pull request #16
Opened 2022-02-23 23:22 UTC by MichelH4cker

## What type of PR is this? (check all applicable)
- [X] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Adicionando o menu lateral.

2022-02-24 14:18 UTC, jorgemrisco commented
#### 📝 Changed routes:


| [**/**](https://ob-site-8tlgf5cet-zenith-aerospace.vercel.app/) |
|:-:|
|<a href="https://ob-site-8tlgf5cet-zenith-aerospace.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/mfa4zLe3DcKLqpejsB_nymJDgxCcC_Tp5yGvlOHUEdbcquAUxIAUUzH0WYaMltgMJQ2zX_a5g0k8RkQDSBqpPw.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/yIa9xzjHiBuHWGAzItat65QiBHVKHm9oGEOLRWIA_0EmtxhLq8cnVc42EoIzyM0Q1CbDoy25QRmZmZ-P23DCxQ.png">(view full size)</a> |







Commit f062c8304db153b543a1662cf4aae94e30679c98 (https://ob-site-8tlgf5cet-zenith-aerospace.vercel.app).

2022-02-24 20:31 UTC, mairacanal requested changes
Algumas perguntas:
- O arquivo `README.md` pertence a esse PR?
- Os arquivos `package-lock.json` e `package.json` pertencem a esse PR?

Coisas que devem ser mudadas:
- Logo do Zenith (usar o sem sombra)
- A largura do SideMenu (na minha tela, particulamente, está muito grande)
- Mudar o tom de verde
- Centralizar mais os logos do Zenith e da OBSAT

Em geral, o código está muito bom, mas, por outro lado, o histórico de commits está uma bagunça absoluta (tem commit em português, em letra maiúscula, em letra minúscula e etc). O padrão de commits do Zenith não foi utilizado. Sendo assim, pesquisem sobre `git rebase -i` para consertar o histórico de commits de vocês.

2022-02-24 20:31 UTC, mairacanal commented on components/DataTeam.jsx
> +import {BsUpload} from 'react-icons/bs';
Isso não está sendo utilizado no arquivo.

2022-02-24 20:31 UTC, mairacanal commented on components/Footer.jsx
> +import zenithLogo from '../public/images/logo-zenith.png'
Isso não está sendo utilizado no arquivo

2022-02-24 20:31 UTC, mairacanal commented on components/Footer.jsx
> +            <img
Tentem utilizar o `next/image` ao invés do `img` por motivos de optimização.

Referência: https://nextjs.org/docs/api-reference/next/image

2022-02-24 20:31 UTC, mairacanal commented on components/HorizontalLine.jsx
> +export default function SideMenu() {
Por que o nome da função é `SideMenu` ao invés de `HorizontalLine`, considerando o que ela representa?

2022-02-24 20:31 UTC, mairacanal commented on components/PackageGrid.jsx
> +      <div className={styles.title}>Dados Recebidos</div>
Definam um padrão para nome de classe CSS. Nessa linha, vocês usam `title` com letra minúscula e, em outra linha, vocês utilizam `WrapperGrid` com letra maiúscula.

2022-02-24 20:31 UTC, mairacanal commented on pages/index.jsx
> +//  import Head from "next/head";
Por que essa linha comentada existe?

2022-02-24 20:31 UTC, mairacanal commented on styles/Packages.module.css
> +.WrapperGrid{
Lembrem-se do padrão de nomenclatura estabelecido.

2022-03-03 18:51 UTC, jorgemrisco commented
#### 📝 Changed routes:


| [**/**](https://ob-site-6euk2g17c-zenith-aerospace.vercel.app/) |
|:-:|
|<a href="https://ob-site-6euk2g17c-zenith-aerospace.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/dc1xeVApwg_Vn-DHeLDF7AGKokL25M7s0nDT2LiohOKkVxnBwckEnHpr9bCM3IDfOLr-3nYTOYF0wTVEF0riEg.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/7BbOn5dpm6lmMOIHjOvKhUGp3Uuiq7rBp--TZ4h8Dv6cSbe0I504us2fPH8i2SAlo7QAzbf94zvL01MSBJyqNQ.png">(view full size)</a> |







Commit 1f6a82238af8eee5a43d4cc73fec8f6eaef520fa (https://ob-site-6euk2g17c-zenith-aerospace.vercel.app).

2022-03-15 11:20 UTC, mairacanal commented
O deploy deu erro, como pode ser visto no log da vercel.

2022-03-16 11:14 UTC, mairacanal requested changes
Tá perfeito, só falta colocar o s-o-b do Michel e do Torrent.

2022-03-23 15:58 UTC, mairacanal approved these changes

2022-03-24 22:42 UTC, Grillo-0 approved these changes

2022-03-25 11:25 UTC, merged