Api/data encoder
zenitheesc/Obsite pull request #22
Opened 2022-08-01 05:19 UTC by Math-42

## What type of PR is this? (check all applicable)
- [x] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Cria uma API para que os participantes possam enviar seus dados e testar na plataforma original.

# Testing

2022-08-01 11:37 UTC, mairacanal commented on components/side-menu.jsx
> +        console.log(data)
Precisa disso?

2022-08-01 11:45 UTC, mairacanal requested changes

2022-08-01 11:45 UTC, mairacanal commented on pages/api/data-encoder.js
> +
Espaçamento estranho

2022-08-01 11:45 UTC, mairacanal commented on pages/api/data-encoder.js
> +    "equipe": byteArray[0],
Esse "equipe" em português não ficou meio deslocado do resto do JSON em inglês?

2022-08-01 11:45 UTC, mairacanal commented on pages/api/data-encoder.js
> +export default function saveProbeData(req, res) {
Essa função merece uns espaços, não acha? Só para melhorar a legibilidade.

2022-08-01 11:45 UTC, mairacanal commented on pages/api/data-encoder.js
> +    sendBytes(getTodayDate(), dataPackage.equipe, dataPackage);
No estilo mais AMD de ser, se o id tá dentro de `dataPackage`, por que você está passando ambos?

2022-08-01 11:45 UTC, mairacanal commented on pages/api/data-encoder.js
> +
Apagar.

2022-08-01 18:34 UTC, Math-42 commented on pages/api/data-encoder.js
> +    "equipe": byteArray[0],
tem que ser assim, pq todo o resto da infraestrutura está assim, serverd, json dos participantes, zenith monitor e etc.

2022-08-01 18:37 UTC, Math-42 commented on pages/api/data-encoder.js
> +    sendBytes(getTodayDate(), dataPackage.equipe, dataPackage);
A função sendBytes pode ser usada para enviar qualquer tipo de dado para o firebase, não necessariametne um dataPacakge igual esse que contem o id. Fiz assim só para manter o código genérico.

2022-08-01 18:37 UTC, Math-42 commented on pages/api/data-encoder.js
> +
Apagar o que exatamente e pq?

2022-08-01 18:58 UTC, mairacanal commented on pages/api/data-encoder.js
> +
Apagar a linha a mais.

2022-08-02 11:43 UTC, mairacanal approved these changes

2022-08-02 19:46 UTC, Grillo-0 approved these changes

2022-08-02 20:04 UTC, merged